# Generated by Django 5.0.9 on 2024-10-05 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cep', models.IntegerField()),
                ('rua', models.CharField(max_length=255)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
