# Generated by Django 5.0.9 on 2024-10-05 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enderecos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='endereco',
            table='endereco',
        ),
    ]
