# Generated by Django 5.1.1 on 2024-11-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_remove_perfil_usuario_id_perfil_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='nome',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
