# Generated by Django 5.1.3 on 2024-11-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0002_alter_avaliacao_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='comentario',
            field=models.TextField(max_length=200),
        ),
    ]
