# Generated by Django 5.1.1 on 2024-10-24 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Autenticacao',
        ),
    ]
