# Generated by Django 5.1.1 on 2024-09-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud1', '0002_pessoa_delete_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='dt_nasc',
            field=models.DateField(blank=True, null=True),
        ),
    ]
