# Generated by Django 5.1.1 on 2024-09-27 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud1', '0003_alter_pessoa_dt_nasc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
